# Generated by Django 5.2 on 2025-05-08 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneraterVideImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='My_Image', max_length=200)),
                ('status', models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], max_length=100)),
                ('generater_video_image', models.ImageField(default='images/default.pdf', upload_to='images/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='Unknown', max_length=200)),
                ('video_id', models.CharField(max_length=200)),
                ('download_link', models.URLField(unique=True)),
                ('time_created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_email', models.EmailField(max_length=200)),
                ('subscription_status', models.CharField(choices=[('free', 'free'), ('Standard', 'Standard'), ('Advanced', 'Advanced'), ('Premium', 'Premium')], max_length=100)),
                ('profile_image', models.CharField(blank=True, max_length=500, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_video', models.ManyToManyField(blank=True, to='User.videos')),
            ],
        ),
    ]
