# Generated by Django 5.2.1 on 2025-05-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Telegram chat ID for notifications', max_length=50, null=True),
        ),
    ]
