# Generated by Django 5.2.1 on 2025-05-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_userinfo_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatervideimage',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=100),
        ),
    ]
