# Generated by Django 5.2 on 2025-05-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_generatervideimage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatervideimage',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], max_length=100),
        ),
    ]
